# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.7742, 0.0020, 0.9249, 0.8543, 0.7073, 0.2626, 0.1466],
         [0.9163, 0.9705, 0.2503, 0.3981, 0.2383, 0.1369, 0.1985],
         [0.3353, 0.9260, 0.1565, 0.3908, 0.3866, 0.6408, 0.2934],
         [0.6044, 0.4636, 0.3981, 0.1052, 0.8188, 0.5964, 0.3305],
         [0.8456, 0.7010, 0.0847, 0.5709, 0.0108, 0.6307, 0.6894],
         [0.4637, 0.6537, 0.9747, 0.4815, 0.8186, 0.1440, 0.8334],
         [0.7788, 0.5819, 0.6793, 0.2141, 0.6950, 0.7259, 0.9879]]),
 torch.Size([7, 7]))

melakukan import torch dan membuat random tensor 7x7

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
Y = torch.rand(size=(1, 7))
Z = torch.matmul(X, Y.T) # no error because of transpose
Z, Z.shape


(tensor([[1.8629],
         [1.3025],
         [1.0037],
         [1.4649],
         [1.4229],
         [2.0657],
         [2.2467]]),
 torch.Size([7, 1]))

membuat tensor lagi secara random dengan size 1x7 dan melakukan perkalian matriks dan harus transpose untuk tensor kedua agar tidak error dan mellihat shapenya

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

torch.manual_seed(0): Mengatur seed (benih) untuk generator angka acak PyTorch sehingga nilai acak yang dihasilkan dapat direproduksi. Dengan seed yang sama, angka acak akan sama pada setiap eksekusi.

X = torch.rand(size=(7, 7)): Membuat tensor X berukuran 7x7 yang diisi dengan angka acak dari distribusi seragam (uniform distribution) antara 0 dan 1.

Y = torch.rand(size=(1, 7)): Membuat tensor Y berukuran 1x7 yang diisi dengan angka acak dari distribusi seragam antara 0 dan 1.

Z = torch.matmul(X, Y.T): Melakukan perkalian matriks antara tensor X dan transpos dari tensor Y. .T digunakan untuk melakukan transposisi pada tensor Y.

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:

# Set random seed on the GPU
torch.cuda.manual_seed(1234)


melakukan set random seed ke GPU 1234


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

torch.manual_seed(1234): Menetapkan seed (benih) untuk generator angka acak PyTorch, memastikan bahwa nilai acak yang dihasilkan dapat direproduksi saat menggunakan fungsi-fungsi acak PyTorch.

device = "cuda" if torch.cuda.is_available() else "cpu": Mengecek apakah akses ke GPU tersedia dalam lingkungan saat ini. Jika GPU tersedia, variabel device diatur ke "cuda" yang mengindikasikan penggunaan GPU; jika tidak, maka akan diatur ke "cpu" untuk menggunakan CPU.

torch.rand(size=(2,3)).to(device): Membuat tensor acak dengan ukuran 2x3 dan memindahkannya ke perangkat yang telah ditentukan sebelumnya (GPU jika tersedia, atau CPU jika tidak).


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:

# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

torch.matmul(tensor_A, tensor_B.T): Melakukan operasi perkalian matriks antara tensor_A (sebuah tensor 2x3) dan transpos dari tensor_B (sebuah tensor 2x3). .T digunakan untuk melakukan transposisi pada tensor_B, mengubah tensor tersebut menjadi matriks 3x2 sebelum melakukan perkalian matriks.

### 8. Find the maximum and minimum values of the output of 7.

In [12]:
# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

torch.max(tensor_C): Mengembalikan nilai maksimum dari seluruh elemen dalam tensor tensor_C.
torch.min(tensor_C): Mengembalikan nilai minimum dari seluruh elemen dalam tensor tensor_C.

### 9. Find the maximum and minimum index values of the output of 7.

In [8]:

# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

torch.argmax(tensor_C): Mengembalikan indeks dari nilai maksimum dalam tensor tensor_C. Ini mengembalikan indeks dari nilai terbesar dalam tensor, yang menunjukkan posisi di mana nilai maksimum tersebut terletak.

torch.argmin(tensor_C): Mengembalikan indeks dari nilai minimum dalam tensor tensor_C. Ini mengembalikan indeks dari nilai terkecil dalam tensor, menunjukkan posisi di mana nilai minimum tersebut terletak.


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:

# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


torch.manual_seed(7): Ini mengatur seed (benih) untuk generator angka acak PyTorch, memastikan bahwa nilai acak yang dihasilkan akan sama saat seed yang sama digunakan.

tensor_D = torch.rand(size=(1, 1, 1, 10)): Membuat tensor acak tensor_D dengan ukuran (1, 1, 1, 10). Ini menghasilkan tensor dengan dimensi empat, dengan satu dimensi memiliki panjang 10 dan dimensi-dimensi lainnya memiliki panjang 1.

tensor_E = tensor_D.squeeze(): Operasi squeeze() digunakan untuk menghapus dimensi-dimensi yang memiliki panjang 1 dari tensor. Dalam kasus ini, karena semua dimensi kecuali yang terakhir memiliki panjang 1, maka operasi squeeze() akan menghasilkan tensor dengan dimensi yang lebih rendah (yaitu, menghilangkan dimensi yang tidak perlu).